File         =  {
    SOI ~ Anything? ~ (Snippet ~ Anything)* ~ EOI
}

Identifier   = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }

Marker_start = _{ "// marker-start " }
Marker_end   = _{ "// marker-end " }

Snippet_text =  { (!Marker_end ~ ANY)* }
Anything     = _{ (!Marker_start ~ ANY)* }

Snippet      =  { Marker_start ~ PUSH(Identifier) ~ NEWLINE ~ Snippet_text ~ Marker_end ~ POP ~ NEWLINE }
