file         =  {
    SOI ~ anything ~ (snippet ~ anything)* ~ EOI
}
snippet      =  { marker_start ~ PUSH(identifier) ~ NEWLINE ~ snippet_text ~ marker_end ~ POP ~ NEWLINE }
snippet_text =  { (!marker_end ~ ANY)* }
anything     =  _{ (!marker_start ~ ANY)* }
identifier   = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
marker_start =  _{ "// marker-start " }
marker_end   =  _{ "// marker-end " }
